In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr[0]

1

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2[0][0]

1

In [6]:
arr2[0][2]

3

In [7]:
type(arr2)

numpy.ndarray

In [8]:
arr2.shape

(2, 3)

In [9]:
arr.shape

(5,)

In [10]:
arr.dtype

dtype('int32')

In [11]:
list_arr=np.array([['a','b','c'],['A','B','C'],[1,2,3]])

In [12]:
list_arr

array([['a', 'b', 'c'],
       ['A', 'B', 'C'],
       ['1', '2', '3']], dtype='<U11')

In [13]:
list_arr.size

9

In [14]:
list_arr.shape

(3, 3)

In [15]:
list_arr.dtype

dtype('<U11')

In [16]:
zr=np.zeros((3,3))

In [17]:
zr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arng=np.arange(1,10)
arng

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arng2=np.arange(2,20)
arng2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
arng3=np.arange(10,20)
arng3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
lspace=np.linspace(0,3,30)
lspace

array([0.        , 0.10344828, 0.20689655, 0.31034483, 0.4137931 ,
       0.51724138, 0.62068966, 0.72413793, 0.82758621, 0.93103448,
       1.03448276, 1.13793103, 1.24137931, 1.34482759, 1.44827586,
       1.55172414, 1.65517241, 1.75862069, 1.86206897, 1.96551724,
       2.06896552, 2.17241379, 2.27586207, 2.37931034, 2.48275862,
       2.5862069 , 2.68965517, 2.79310345, 2.89655172, 3.        ])

In [22]:
lspace2=np.linspace(0,30,3)
lspace2

array([ 0., 15., 30.])

In [23]:
emp=np.empty((3,3))
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.54932307e-321],
       [7.56592337e-307, 9.34588060e-307, 3.62651150e-317]])

In [24]:
emp_like=np.empty_like(arr2)
emp_like

array([[         0,          0,          0],
       [1076756480,          0, 1077805056]])

In [25]:
idt3=np.identity(3)
idt3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
idt3.shape

(3, 3)

In [27]:
idt3.reshape(1,9)

array([[1., 0., 0., 0., 1., 0., 0., 0., 1.]])

In [28]:
idt3.ravel()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [29]:
new_arr=np.arange(25)

In [30]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
new_arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
new_arr[0]

0

In [33]:
new_arr.sum(axis=0)

300

In [34]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
new_arr=new_arr.reshape(5,5)

In [36]:
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
new_arr[0]

array([0, 1, 2, 3, 4])

In [38]:
new_arr.sum(axis=0)

array([50, 55, 60, 65, 70])

In [39]:
new_arr.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [40]:
new_arr.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [41]:
new_arr.flat

In [42]:
new_arr.ndim

2

In [47]:
Q=np.array([50,20,30,10,8,45,15,75,100])
Q

array([ 50,  20,  30,  10,   8,  45,  15,  75, 100])

In [48]:
Q

array([ 50,  20,  30,  10,   8,  45,  15,  75, 100])

In [49]:
Q.argmax()

8

In [50]:
Q.argmin()

4

In [51]:
Q.argsort()

array([4, 3, 6, 1, 2, 5, 0, 7, 8], dtype=int64)

In [52]:
Q.sum

<function ndarray.sum>

In [53]:
Q.sum()

353

In [54]:
Q.argmin()

4

In [55]:
np.where(Q>5)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [56]:
np.count_nonzero(Q)

9