In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4,5]])

In [3]:
a

array([[1, 2, 3, 4, 5]])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.size

5

In [7]:
a.dtype

dtype('int32')

In [8]:
a[0][1]

2

In [9]:
a.shape

(1, 5)

In [10]:
b=np.array([['A','B','C'],['A','B','C'],['A','B','C']])

In [12]:
b

array([['A', 'B', 'C'],
       ['A', 'B', 'C'],
       ['A', 'B', 'C']], dtype='<U1')

In [13]:
b.dtype

dtype('<U1')

In [15]:
b.size

9

In [16]:
b.shape

(3, 3)

In [17]:
b[2][2]

'C'

In [18]:
b[0][2]='K'

In [19]:
b

array([['A', 'B', 'K'],
       ['A', 'B', 'C'],
       ['A', 'B', 'C']], dtype='<U1')

In [21]:
z=np.zeros((3,3))

In [22]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
z=np.array(b)
z

array([['A', 'B', 'K'],
       ['A', 'B', 'C'],
       ['A', 'B', 'C']], dtype='<U1')

In [27]:
l=np.linspace(1,10,6)
l

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [28]:
lnd=np.linspace(2,8,4)
lnd

array([2., 4., 6., 8.])

In [29]:
lrd=np.linspace(3,15,10)
lrd

array([ 3.        ,  4.33333333,  5.66666667,  7.        ,  8.33333333,
        9.66666667, 11.        , 12.33333333, 13.66666667, 15.        ])

In [30]:
lrth=np.linspace(1,10,11)
lrth

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [32]:
emp=np.empty((3,3))
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
idt=np.identity(4)
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
arg=np.arange(100)
arg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
arg=arg.resize(10,10)
resize

In [37]:
resize

In [38]:
print(resize)

None


In [39]:
arg

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [40]:
arg.ravel
arg

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
idt.ravel
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
x=np.array([[1,2,3],[8,7,9],[4,2,3]])
x

array([[1, 2, 3],
       [8, 7, 9],
       [4, 2, 3]])

In [43]:
x.sum(axis=0)

array([13, 11, 15])

In [44]:
x.sum(axis=1)

array([ 6, 24,  9])

In [45]:
x.T

array([[1, 8, 4],
       [2, 7, 2],
       [3, 9, 3]])

In [46]:
x

array([[1, 2, 3],
       [8, 7, 9],
       [4, 2, 3]])

In [47]:
x=x.T

In [48]:
x

array([[1, 8, 4],
       [2, 7, 2],
       [3, 9, 3]])

In [49]:
x.sum(axis=0)

array([ 6, 24,  9])

In [50]:
A=np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [51]:
A.size

5

In [52]:
A.shape

(5,)

In [53]:
A.dtype

dtype('int32')

In [54]:
B=np.array([1456,78894,454545,100000000])
B

array([     1456,     78894,    454545, 100000000])

In [55]:
B.size

4

In [56]:
B.shape

(4,)

In [57]:
B.dtype

dtype('int32')

In [58]:
C=np.array([1000000000000000000000000000000,200000000000000000000000000000])
C

array([1000000000000000000000000000000, 200000000000000000000000000000],
      dtype=object)

In [59]:
C.dtype

dtype('O')

In [62]:
D=np.zeros((10,10))

In [63]:
D

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
E=np.identity(5)
E

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
arng=np.arange(12)

In [66]:
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
rearng=arng.reshape(4,3)
rearng

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
x=y=rearng
x
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
x+y

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [72]:
x*y

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [75]:
x-y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [76]:
2*x

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [77]:
4*y

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32],
       [36, 40, 44]])

In [78]:
z=y.ravel()

In [79]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
H=np.identity(3)

In [81]:
H

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
I=H.ravel()
I

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [89]:
print("''")

''


In [90]:
from tkinter import *

In [91]:
root=Tk()
root.mainloop()

In [96]:
root=Tk()

In [97]:
root.geometry('500x500')
root.title("Harpal GUI")
root.mainloop()

In [98]:
Arng=np.arange(55)
Arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54])

In [99]:
R=Arng.reshape(11,5)
R

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [100]:
R=Arng.reshape(5,11)
R

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [101]:
R.T

array([[ 0, 11, 22, 33, 44],
       [ 1, 12, 23, 34, 45],
       [ 2, 13, 24, 35, 46],
       [ 3, 14, 25, 36, 47],
       [ 4, 15, 26, 37, 48],
       [ 5, 16, 27, 38, 49],
       [ 6, 17, 28, 39, 50],
       [ 7, 18, 29, 40, 51],
       [ 8, 19, 30, 41, 52],
       [ 9, 20, 31, 42, 53],
       [10, 21, 32, 43, 54]])

In [102]:
R.sum(axis=0)

array([110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160])

In [103]:
R.sum(axis=1)

array([ 55, 176, 297, 418, 539])