In [1]:
import pandas as pd
import numpy as np

In [2]:
print("Hello World")

Hello World


In [4]:
print("'harpal' is Great")

'harpal' is Great


In [5]:
arr=np.array([12,25,89,100],np.int64)

In [6]:
arr

array([ 12,  25,  89, 100], dtype=int64)

In [7]:
arr[0]

12

In [8]:
arr[2]

89

In [10]:
arr.shape

(4,)

In [11]:
arr=np.array([[1,2,3],[4,5,6]])


In [12]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
arr.shape

(2, 3)

In [14]:
arr[1][0]

4

In [15]:
arr.dtype

dtype('int32')

In [16]:
arr.size

6

In [19]:
zeros=np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeros[0][0]=15

In [22]:
zeros

array([[15.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
zeros.dtype

dtype('float64')

In [24]:
zeros.shape

(2, 3)

In [25]:
zeros.size

6

In [35]:
lnspace=np.linspace(1,5,5)

In [37]:
lnspace

array([1., 2., 3., 4., 5.])

In [39]:
emp=np.empty((4,6))

emp

array([[4.67296746e-307, 1.69121096e-306, 1.60218491e-306,
        6.23057349e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23036978e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [7.56601165e-307, 1.69118787e-306, 9.34609790e-307,
        1.33511562e-306, 1.11260144e-306, 2.22522596e-306]])

In [42]:
arr_arng=np.arange(199)
arr_arng

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [43]:
arng=np.arange(100)
arng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
divide=arng.reshape(10,10)
divide

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
divide.size

100

In [ ]:
divide[3][]